resources:
  - name: npm_project
    type: GitRepo
    configuration:
      gitProvider: ranjan_github
      path: ranjansingh41/test      
  - name: npm_build_info
    type: BuildInfo
    configuration:
      sourceArtifactory: ranjan_artifactory
      buildNumber: 1
      buildName: npm-testing

pipelines:
  - name: test_pipeline11112
    steps:
      - name: start_npm_build
        type: NpmBuild
        configuration:
          repositoryName: ranjan_npm_test
          sourceLocation: .
          inputResources:
            - name: npm_project
          integrations:
            - name: ranjan_artifactory
            
      - name: start_npm_pub_autopub_true
        type: NpmPublish
        configuration:
          repositoryName: ranjan_npm_local
          autoPublishBuildInfo: true
          inputSteps:
            - name: start_npm_build
#           integrations:
#             - name: ranjan_artifactory
          outputResources:
            - name: npm_build_info
